version: '3.4'
services:
  server:
    restart: always
    ports:
      - "4000:4000"
    build:
      dockerfile: Dockerfile
      context: .
  client:
    network_mode: host
    restart: always
    depends_on:
      - server
    build:
      dockerfile: Dockerfile2
      context: .
